import { FIXTURE_FONT_FAMILY, type CanvasScene } from "./scene.js";

const fullTurn = Math.PI * 2;

export const curatedScenes: CanvasScene[] = [
  {
    name: "rectangles-alpha-and-compositing",
    background: "#151820",
    commands: [
      { type: "setFillColor", color: "#ff4068" },
      { type: "fillRect", x: 12, y: 14, width: 72, height: 58 },
      { type: "setGlobalAlpha", alpha: 0.62 },
      { type: "setFillColor", color: "#45a0ff" },
      { type: "fillRect", x: 48, y: 42, width: 68, height: 70 },
      { type: "setGlobalAlpha", alpha: 1 },
      { type: "setComposite", operation: "lighter" },
      { type: "setFillColor", color: "#85ff38" },
      { type: "fillRect", x: 28, y: 78, width: 70, height: 28 },
    ],
  },
  {
    name: "clip-wide-and-local-destructive-compositing",
    background: "#151820",
    commands: [
      { type: "setFillColor", color: "#d2ff45" },
      { type: "fillRect", x: 12, y: 12, width: 60, height: 52 },
      { type: "setComposite", operation: "source-in" },
      { type: "setFillColor", color: "#6954ff" },
      { type: "fillRect", x: 42, y: 30, width: 72, height: 62 },
      { type: "setComposite", operation: "source-over" },
      { type: "setFillColor", color: "#ff4f79" },
      { type: "fillRect", x: 20, y: 82, width: 88, height: 30 },
      { type: "clearRect", x: 48, y: 88, width: 30, height: 18 },
    ],
  },
  {
    name: "full-clear-respects-the-active-clip",
    background: "#151820",
    commands: [
      { type: "setFillColor", color: "#d2ff45" },
      { type: "fillRect", x: 8, y: 8, width: 112, height: 112 },
      { type: "save" },
      { type: "beginPath" },
      { type: "roundRect", x: 34, y: 30, width: 60, height: 68, radii: [14] },
      { type: "clip", rule: "nonzero" },
      { type: "clearRect", x: 0, y: 0, width: 128, height: 128 },
      { type: "restore" },
    ],
  },
  {
    name: "curves-arcs-and-rounded-rectangles",
    background: "#101218",
    commands: [
      { type: "setFillColor", color: "#815cff" },
      { type: "beginPath" },
      { type: "moveTo", x: 12, y: 92 },
      { type: "bezierCurveTo", control1X: 20, control1Y: 12, control2X: 76, control2Y: 8, x: 84, y: 72 },
      { type: "arcTo", x1: 92, y1: 108, x2: 116, y2: 78, radius: 14 },
      { type: "lineTo", x: 112, y: 110 },
      { type: "closePath" },
      { type: "fill", rule: "nonzero" },
      { type: "setFillColor", color: "rgba(207,255,64,0.86)" },
      { type: "beginPath" },
      { type: "ellipse", x: 92, y: 38, radiusX: 24, radiusY: 14, rotation: 0.35, start: 0, end: fullTurn, counterclockwise: false },
      { type: "fill", rule: "nonzero" },
      { type: "setFillColor", color: "rgba(255,87,126,0.82)" },
      { type: "beginPath" },
      { type: "roundRect", x: 16, y: 18, width: 52, height: 36, radii: [14, 3, 12, 7] },
      { type: "fill", rule: "nonzero" },
    ],
  },
  {
    name: "save-restore-and-transforms",
    background: "#17151e",
    commands: [
      { type: "translate", x: 64, y: 64 },
      { type: "save" },
      { type: "rotate", radians: 0.42 },
      { type: "scale", x: 1.2, y: 0.72 },
      { type: "setFillColor", color: "#ceff42" },
      { type: "fillRect", x: -40, y: -28, width: 80, height: 56 },
      { type: "restore" },
      { type: "rotate", radians: -0.35 },
      { type: "setFillColor", color: "rgba(102,76,255,0.72)" },
      { type: "fillRect", x: -16, y: -52, width: 32, height: 104 },
      { type: "resetTransform" },
      { type: "setFillColor", color: "#ff527c" },
      { type: "fillRect", x: 8, y: 104, width: 112, height: 10 },
    ],
  },
  {
    name: "strokes-caps-joins-and-dashes",
    background: "#121419",
    commands: [
      { type: "setStrokeColor", color: "#d2ff45" },
      { type: "setStroke", width: 7, cap: "round", join: "round", miterLimit: 4 },
      { type: "setLineDash", intervals: [17, 7, 3, 7], offset: 2 },
      { type: "beginPath" },
      { type: "moveTo", x: 12, y: 96 },
      { type: "quadraticCurveTo", controlX: 38, controlY: 18, x: 70, y: 68 },
      { type: "lineTo", x: 112, y: 24 },
      { type: "stroke" },
      { type: "setStrokeColor", color: "rgba(255,75,118,0.86)" },
      { type: "setStroke", width: 3, cap: "square", join: "miter", miterLimit: 6 },
      { type: "setLineDash", intervals: [], offset: 0 },
      { type: "strokeRect", x: 24, y: 78, width: 76, height: 34 },
    ],
  },
  {
    name: "gradients-clips-and-destination-read",
    background: "#12131a",
    commands: [
      { type: "beginPath" },
      { type: "roundRect", x: 12, y: 12, width: 104, height: 104, radii: [22, 5, 30, 12] },
      { type: "clip", rule: "nonzero" },
      {
        type: "setFillLinearGradient",
        points: [10, 10, 118, 118],
        stops: [
          { offset: 0, color: "#d5ff47" },
          { offset: 0.48, color: "#6750ff" },
          { offset: 1, color: "#ff4f79" },
        ],
      },
      { type: "fillRect", x: 0, y: 0, width: 128, height: 128 },
      { type: "setComposite", operation: "multiply" },
      { type: "setFillColor", color: "rgba(52,170,255,0.78)" },
      { type: "beginPath" },
      { type: "arc", x: 76, y: 58, radius: 42, start: 0, end: fullTurn, counterclockwise: false },
      { type: "fill", rule: "nonzero" },
    ],
  },
  {
    name: "translucent-gradient-interpolation",
    background: "#101218",
    commands: [
      {
        type: "setFillLinearGradient",
        points: [8, 64, 120, 64],
        stops: [
          { offset: 0, color: "rgba(255,79,121,1)" },
          { offset: 0.5, color: "rgba(83,213,255,0.18)" },
          { offset: 1, color: "rgba(210,255,69,0.72)" },
        ],
      },
      { type: "fillRect", x: 8, y: 20, width: 112, height: 88 },
    ],
  },
  {
    name: "fixed-font-fill-and-stroke-text",
    background: "#11131a",
    commands: [
      { type: "setFont", value: `32px '${FIXTURE_FONT_FAMILY}'` },
      { type: "setTextBaseline", value: "alphabetic" },
      { type: "setFillColor", color: "#d2ff45" },
      { type: "fillText", text: "hidden", x: 8, y: 18, maxWidth: 0 },
      { type: "fillText", text: "Valo", x: 8, y: 42 },
      { type: "setFont", value: `34px '${FIXTURE_FONT_FAMILY}'` },
      { type: "setTextAlign", value: "center" },
      { type: "setStrokeColor", color: "#ff4f79" },
      { type: "setStroke", width: 2, cap: "round", join: "round", miterLimit: 4 },
      { type: "strokeText", text: "Canvas", x: 64, y: 84, maxWidth: 108 },
      { type: "setFont", value: `18px '${FIXTURE_FONT_FAMILY}'` },
      { type: "setTextSpacing", letter: "1px", word: "2px" },
      { type: "setFillColor", color: "#35a7ff" },
      { type: "fillText", text: "fixed font", x: 64, y: 112 },
    ],
  },
  {
    name: "fixed-image-crops-scaling-and-pattern",
    background: "#12151c",
    commands: [
      { type: "drawImage", arguments: [8, 8] },
      { type: "drawImage", arguments: [32, 8, 44, 32] },
      { type: "drawImage", arguments: [4, 4, 8, 8, 84, 8, 36, 36] },
      {
        type: "setFillPattern",
        repetition: "repeat",
        transform: [0.75, 0, 0, 0.75, 5, 3],
      },
      { type: "beginPath" },
      { type: "roundRect", x: 8, y: 58, width: 112, height: 60, radii: [14, 4, 14, 4] },
      { type: "fill", rule: "nonzero" },
    ],
  },
  {
    name: "shadows-and-clear-rect",
    background: "#151820",
    commands: [
      { type: "setShadow", color: "rgba(0,0,0,0.72)", blur: 8, offsetX: 6, offsetY: 7 },
      { type: "setFillColor", color: "#6954ff" },
      { type: "beginPath" },
      { type: "roundRect", x: 24, y: 22, width: 72, height: 62, radii: [16] },
      { type: "fill", rule: "nonzero" },
      { type: "setShadow", color: "transparent", blur: 0, offsetX: 0, offsetY: 0 },
      { type: "setFillColor", color: "#ff4f79" },
      { type: "fillRect", x: 12, y: 96, width: 104, height: 20 },
      { type: "clearRect", x: 48, y: 92, width: 32, height: 28 },
    ],
  },
  {
    name: "shadows-stay-in-device-space-under-transform",
    background: "#151820",
    commands: [
      { type: "translate", x: 60, y: 56 },
      { type: "rotate", radians: 0.48 },
      { type: "scale", x: 1.55, y: 0.68 },
      { type: "setShadow", color: "rgba(0,0,0,0.76)", blur: 10, offsetX: 9, offsetY: 7 },
      { type: "setFillColor", color: "#d2ff45" },
      { type: "beginPath" },
      { type: "roundRect", x: -26, y: -22, width: 52, height: 44, radii: [9] },
      { type: "fill", rule: "nonzero" },
    ],
  },
  {
    name: "copy-applies-to-shadow-and-shape-separately",
    background: "#151820",
    commands: [
      { type: "setFillColor", color: "#35a7ff" },
      { type: "fillRect", x: 8, y: 8, width: 112, height: 112 },
      { type: "setComposite", operation: "copy" },
      { type: "setShadow", color: "rgba(255,79,121,0.9)", blur: 6, offsetX: 12, offsetY: 10 },
      { type: "setFillColor", color: "#d2ff45" },
      { type: "fillRect", x: 28, y: 30, width: 54, height: 46 },
    ],
  },
  {
    name: "ordered-css-color-filter-chain",
    background: "#151820",
    commands: [
      { type: "setFilter", value: "sepia(70%) hue-rotate(38deg) saturate(1.35) opacity(78%)" },
      {
        type: "setFillLinearGradient",
        points: [18, 20, 108, 104],
        stops: [
          { offset: 0, color: "#ff4f79" },
          { offset: 0.5, color: "#35a7ff" },
          { offset: 1, color: "#d2ff45" },
        ],
      },
      { type: "fillRect", x: 18, y: 20, width: 90, height: 84 },
    ],
  },
  {
    name: "css-blur-then-contrast",
    background: "#151820",
    commands: [
      { type: "setFilter", value: "blur(4px) contrast(1.25)" },
      { type: "setFillColor", color: "#d2ff45" },
      { type: "fillRect", x: 30, y: 32, width: 58, height: 52 },
    ],
  },
  {
    name: "css-filter-with-canvas-shadow",
    background: "#151820",
    commands: [
      { type: "setFilter", value: "blur(2px) grayscale(45%)" },
      { type: "setShadow", color: "rgba(255,79,121,0.84)", blur: 5, offsetX: 9, offsetY: 7 },
      { type: "setFillColor", color: "#d2ff45" },
      { type: "fillRect", x: 30, y: 30, width: 56, height: 50 },
    ],
  },
  {
    name: "css-blur-under-nonuniform-transform",
    background: "#151820",
    commands: [
      { type: "translate", x: 62, y: 62 },
      { type: "rotate", radians: 0.42 },
      { type: "scale", x: 1.55, y: 0.68 },
      { type: "setFilter", value: "blur(4px)" },
      { type: "setFillColor", color: "#d2ff45" },
      { type: "fillRect", x: -24, y: -22, width: 48, height: 44 },
    ],
  },
  {
    name: "css-color-filter-under-transform",
    background: "#151820",
    commands: [
      { type: "translate", x: 62, y: 62 },
      { type: "rotate", radians: 0.42 },
      { type: "scale", x: 1.55, y: 0.68 },
      { type: "setFilter", value: "grayscale(45%)" },
      { type: "setFillColor", color: "#d2ff45" },
      { type: "fillRect", x: -24, y: -22, width: 48, height: 44 },
    ],
  },
  {
    name: "css-blur-under-skew",
    background: "#151820",
    commands: [
      { type: "translate", x: 50, y: 42 },
      { type: "transform", matrix: [1, 0.28, 0.46, 1, 0, 0] },
      { type: "setFilter", value: "blur(4px)" },
      { type: "setFillColor", color: "#d2ff45" },
      { type: "fillRect", x: 0, y: 0, width: 48, height: 44 },
    ],
  },
];
